package com.promenar.nexara.ui.testing

/**
 * 面向自动化测试的稳定语义标识。标识描述控件职责，不依赖本地化文案或动态数据。
 */
object UiTags {
    const val BACKUP_EXPORT = "backup_export"
    const val BACKUP_IMPORT = "backup_import"
    const val BACKUP_OPERATION_STATUS = "backup_operation_status"
    const val CHAT_ROOT = "chat_root"
    const val CHAT_STATE_EMPTY = "chat_state_empty"
    const val CHAT_STATE_LOADING = "chat_state_loading"
    const val CHAT_STATE_GENERATING = "chat_state_generating"
    const val CHAT_STATE_APPROVAL = "chat_state_approval"
    const val CHAT_STATE_ERROR = "chat_state_error"
    const val CHAT_STATE_READY = "chat_state_ready"
    const val CHAT_LOADING_SKELETON = "chat_loading_skeleton"
    const val CHAT_GENERATION_ACTION = "chat_generation_action"
    const val CHAT_COMPOSER = "chat_composer"
    const val CHAT_TASK_PANEL_HEADER = "task_floating_panel_header"
    const val CHAT_THINKING_TRACE = "chat_thinking_trace"
    const val CHAT_THINKING_TOGGLE = "chat_thinking_toggle"
    const val CHAT_THINKING_CONTENT = "chat_thinking_content"
    const val CHAT_INPUT_ISLAND = "chat_input_island"
    const val CHAT_INPUT_BAR_SURFACE = "chat_input_bar_surface"
    const val CHAT_OPTIONS = "chat_options"
    const val CHAT_SESSION_SETTINGS = "chat_session_settings"
    const val CHAT_INPUT = "chat_input"
    const val PROMPT_EDITOR_INPUT = "prompt_editor_input"
    const val CHAT_MODEL_SELECTOR = "chat_model_selector"
    const val CHAT_MODEL_SELECTOR_VISUAL = "chat_model_selector_visual"
    const val CHAT_TOKEN_INDICATOR = "chat_token_indicator"
    const val CHAT_TOKEN_INDICATOR_VISUAL = "chat_token_indicator_visual"
    const val CHAT_MODEL_LIST = "chat_model_list"
    private const val CHAT_MODEL_OPTION_PREFIX = "chat_model_option:"

    fun chatModelOption(modelId: String): String = CHAT_MODEL_OPTION_PREFIX + modelId
    const val CHAT_APPROVAL_CARD = "chat_approval_card"
    const val CHAT_APPROVAL_REQUIRED = "chat_approval_required"
    const val CHAT_APPROVAL_EXECUTED = "chat_approval_executed"
    const val CHAT_APPROVAL_APPROVE = "chat_approval_approve"
    const val CHAT_APPROVAL_DECLINE = "chat_approval_decline"
    const val NOTIFICATION_PERMISSION_DIALOG = "notification_permission_dialog"
    const val NOTIFICATION_PERMISSION_CONTINUE = "notification_permission_continue"
    const val NOTIFICATION_PERMISSION_FOREGROUND_ONLY = "notification_permission_foreground_only"
    const val SHARE_IMPORT_SHEET = "share_import_sheet"
    const val SHARE_IMPORT_ITEM = "share_import_item"
    const val SHARE_IMPORT_STATUS = "share_import_status"
    const val SHARE_IMPORT_KNOWLEDGE_BASE_TARGET = "share_import_knowledge_base_target"
    const val SHARE_IMPORT_LATER = "share_import_later"
    const val SHARE_IMPORT_CANCEL = "share_import_cancel"
    const val SHARE_IMPORT_ACTION = "share_import_action"

    // ============ Agent Hub ==========
    const val HUB_ROOT = "hub_root"
    const val HUB_ADD_AGENT = "hub_add_agent"
    const val HUB_SEARCH = "hub_search"
    const val HUB_EMPTY_STATE = "hub_empty_state"
    const val HUB_EMPTY_ADD_AGENT = "hub_empty_add_agent"
    const val HUB_AGENT_LIST = "hub_agent_list"
    const val HUB_AGENT_ACTIONS = "hub_agent_actions"
    const val HUB_AGENT_MENU_PIN = "hub_agent_menu_pin"
    const val HUB_AGENT_MENU_EDIT = "hub_agent_menu_edit"
    const val HUB_AGENT_MENU_DELETE = "hub_agent_menu_delete"
    private const val HUB_AGENT_CARD_PREFIX = "hub_agent_card:"

    fun hubAgentCard(agentId: String): String = HUB_AGENT_CARD_PREFIX + agentId
    fun hubAgentActions(agentId: String): String = "$HUB_AGENT_ACTIONS:$agentId"

    // ============ User Settings Home ==========
    const val SETTINGS_ROOT = "settings_root"
    const val SETTINGS_TAB_APP = "settings_tab_app"
    const val SETTINGS_TAB_PROVIDER = "settings_tab_provider"
    const val SETTINGS_APP_LIST = "settings_app_list"
    const val SETTINGS_PROVIDER_LIST = "settings_provider_list"
    const val SETTINGS_ADD_PROVIDER = "settings_add_provider"
    const val SETTINGS_PROVIDER_ACTIONS = "settings_provider_actions"
    const val SETTINGS_LOCAL_INFERENCE_ENTRY = "settings_local_inference_entry"
    private const val SETTINGS_PROVIDER_CARD_PREFIX = "settings_provider_card:"

    fun settingsProviderCard(providerId: String): String = SETTINGS_PROVIDER_CARD_PREFIX + providerId
    fun settingsProviderActions(providerId: String): String = "$SETTINGS_PROVIDER_ACTIONS:$providerId"

    // ============ Provider Models ==========
    const val PROVIDER_MODELS_SCREEN_ROOT = "provider_models_screen_root"
    const val PROVIDER_MODELS_SEARCH_FIELD = "provider_models_search"
    const val PROVIDER_MODELS_ACTION_SYNC = "provider_models_action_sync"
    const val PROVIDER_MODELS_ACTION_ADD = "provider_models_action_add"
    const val PROVIDER_MODELS_ACTION_DISABLE_ALL = "provider_models_action_disable_all"
    const val PROVIDER_MODELS_ACTION_DELETE_ALL = "provider_models_action_delete_all"
    const val PROVIDER_MODELS_NOTICE = "provider_models_notice"
    const val PROVIDER_MODELS_NOTICE_DISMISS = "provider_models_notice_dismiss"
    const val PROVIDER_MODELS_LIST = "provider_models_list"
    const val PROVIDER_MODELS_STATE_EMPTY = "provider_models_state_empty"
    const val PROVIDER_MODELS_STATE_ERROR = "provider_models_state_error"
    const val PROVIDER_MODELS_STATE_LOADING = "provider_models_state_loading"
    const val PROVIDER_MODELS_ADD_SHEET = "provider_models_add_sheet"
    const val PROVIDER_MODELS_ADD_ID_FIELD = "provider_models_add_id"
    const val PROVIDER_MODELS_ADD_NAME_FIELD = "provider_models_add_name"
    const val PROVIDER_MODELS_ADD_SUBMIT_BUTTON = "provider_models_add_submit"
    const val PROVIDER_MODELS_DELETE_ALL_CONFIRM_DIALOG = "provider_models_delete_all_confirm_dialog"
    const val PROVIDER_MODELS_DELETE_ALL_CONFIRM_BUTTON = "provider_models_delete_all_confirm"

    private const val PROVIDER_MODELS_MODEL_CARD_PREFIX = "provider_models_card:"
    private const val PROVIDER_MODELS_MODEL_TEST_PREFIX = "provider_models_test:"
    private const val PROVIDER_MODELS_MODEL_DELETE_PREFIX = "provider_models_delete:"
    private const val PROVIDER_MODELS_MODEL_TOGGLE_PREFIX = "provider_models_toggle:"
    private const val PROVIDER_MODELS_TYPE_PREFIX = "provider_models_type:"
    private const val PROVIDER_MODELS_TYPE_VISUAL_PREFIX = "provider_models_type_visual:"
    private const val PROVIDER_MODELS_CAPABILITY_PREFIX = "provider_models_capability:"
    private const val PROVIDER_MODELS_CAPABILITY_VISUAL_PREFIX = "provider_models_capability_visual:"
    private const val PROVIDER_MODELS_CONTEXT_PREFIX = "provider_models_context:"

    fun providerModelsModelCard(modelId: String): String = "$PROVIDER_MODELS_MODEL_CARD_PREFIX$modelId"
    fun providerModelsTestAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_TEST_PREFIX$modelId"
    fun providerModelsDeleteAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_DELETE_PREFIX$modelId"
    fun providerModelsToggleAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_TOGGLE_PREFIX$modelId"
    fun providerModelsTypeAction(modelId: String, type: String): String =
        "$PROVIDER_MODELS_TYPE_PREFIX$modelId:$type"
    fun providerModelsTypeVisual(modelId: String, type: String): String =
        "$PROVIDER_MODELS_TYPE_VISUAL_PREFIX$modelId:$type"
    fun providerModelsCapabilityAction(modelId: String, capability: String): String =
        "$PROVIDER_MODELS_CAPABILITY_PREFIX$modelId:$capability"
    fun providerModelsCapabilityVisual(modelId: String, capability: String): String =
        "$PROVIDER_MODELS_CAPABILITY_VISUAL_PREFIX$modelId:$capability"
    fun providerModelsContextField(modelId: String): String = "$PROVIDER_MODELS_CONTEXT_PREFIX$modelId"

    // ============ RAG Home ==========
    const val RAG_HOME_ROOT = "RAG_HOME_ROOT"
    const val RAG_HOME_SEARCH = "RAG_HOME_SEARCH"
    const val RAG_HOME_TAB_DOCUMENTS = "RAG_HOME_TAB_DOCUMENTS"
    const val RAG_HOME_TAB_MEMORY = "RAG_HOME_TAB_MEMORY"
    const val RAG_HOME_TAB_GRAPH = "RAG_HOME_TAB_GRAPH"
    const val RAG_HOME_CONFIG = "RAG_HOME_CONFIG"
    const val RAG_HOME_NEW_FOLDER = "RAG_HOME_NEW_FOLDER"
    const val RAG_HOME_UPLOAD = "RAG_HOME_UPLOAD"
    const val RAG_HOME_DOCUMENTS_CONTENT = "RAG_HOME_DOCUMENTS_CONTENT"
    const val RAG_HOME_MEMORY_CONTENT = "RAG_HOME_MEMORY_CONTENT"
    const val RAG_HOME_INDEXING_NOTICE = "RAG_HOME_INDEXING_NOTICE"
    const val RAG_HOME_NEW_FOLDER_DIALOG = "RAG_HOME_NEW_FOLDER_DIALOG"
    const val RAG_HOME_MOVE_SHEET = "RAG_HOME_MOVE_SHEET"
    const val RAG_HOME_SELECTION_BAR = "RAG_HOME_SELECTION_BAR"
    const val RAG_HOME_CLEAR_SELECTION = "RAG_HOME_CLEAR_SELECTION"
    const val RAG_HOME_MOVE_SELECTION = "RAG_HOME_MOVE_SELECTION"
    const val RAG_HOME_REINDEX_SELECTION = "RAG_HOME_REINDEX_SELECTION"
    const val RAG_HOME_DELETE_SELECTION = "RAG_HOME_DELETE_SELECTION"
    const val RAG_HOME_DELETE_CONFIRM_DIALOG = "RAG_HOME_DELETE_CONFIRM_DIALOG"
    const val RAG_HOME_DELETE_CONFIRM_BUTTON = "RAG_HOME_DELETE_CONFIRM_BUTTON"

    // ============ Doc Editor ==========
    const val DOC_EDITOR_ROOT = "doc_editor_root"
    const val DOC_EDITOR_BACK = "doc_editor_back"
    const val DOC_EDITOR_TITLE_INPUT = "doc_editor_title_input"
    const val DOC_EDITOR_SAVE = "doc_editor_save"
    const val DOC_EDITOR_MODE_EDIT = "doc_editor_mode_edit"
    const val DOC_EDITOR_MODE_PREVIEW = "doc_editor_mode_preview"
    const val DOC_EDITOR_MODE_SPLIT = "doc_editor_mode_split"
    const val DOC_EDITOR_INPUT = "doc_editor_input"
    const val DOC_EDITOR_PREVIEW = "doc_editor_preview"
    const val DOC_EDITOR_STATUS = "doc_editor_status"
    const val DOC_EDITOR_STATE_LOADING = "doc_editor_state_loading"
    const val DOC_EDITOR_STATE_LOAD_ERROR = "doc_editor_state_load_error"
    const val DOC_EDITOR_STATE_NOT_FOUND = "doc_editor_state_not_found"
    const val DOC_EDITOR_STATE_SAVING = "doc_editor_state_saving"
    const val DOC_EDITOR_STATE_SAVE_ERROR = "doc_editor_state_save_error"
    const val DOC_EDITOR_STATE_CONFLICT = "doc_editor_state_conflict"
    const val DOC_EDITOR_STATE_LARGE_FILE = "doc_editor_state_large_file"
    const val DOC_EDITOR_RETRY_LOAD = "doc_editor_retry_load"
    const val DOC_EDITOR_RETRY_SAVE = "doc_editor_retry_save"
    const val DOC_EDITOR_COPY_LOCAL = "doc_editor_copy_local"
    const val DOC_EDITOR_REQUEST_RELOAD = "doc_editor_request_reload"
    const val DOC_EDITOR_WARNING_DISMISS = "doc_editor_warning_dismiss"
    const val DOC_EDITOR_DISCARD_DIALOG = "doc_editor_discard_dialog"
    const val DOC_EDITOR_DISCARD_CONFIRM = "doc_editor_discard_confirm"
    const val DOC_EDITOR_DISCARD_CANCEL = "doc_editor_discard_cancel"
    const val DOC_EDITOR_RELOAD_DIALOG = "doc_editor_reload_dialog"
    const val DOC_EDITOR_RELOAD_CONFIRM = "doc_editor_reload_confirm"
    const val DOC_EDITOR_RELOAD_CANCEL = "doc_editor_reload_cancel"

    // ============ Resource Explorer ==========
    const val RESOURCE_EXPLORER_ROOT = "resource_explorer_root"
    const val RESOURCE_EXPLORER_SEARCH = "resource_explorer_search"
    const val RESOURCE_EXPLORER_IMPORT = "resource_explorer_import"
    const val RESOURCE_EXPLORER_IMPORT_RESULTS = "resource_explorer_import_results"
    const val RESOURCE_EXPLORER_CLEAR_RESULTS = "resource_explorer_clear_results"
    const val RESOURCE_EXPLORER_TAB_FILES = "resource_explorer_tab_files"
    const val RESOURCE_EXPLORER_TAB_RECYCLE_BIN = "resource_explorer_tab_recycle_bin"
    const val RESOURCE_EXPLORER_PAGER = "resource_explorer_pager"
    const val RESOURCE_EXPLORER_SESSION_STATUS = "resource_explorer_session_status"
    const val RESOURCE_EXPLORER_RETRY_LOAD = "resource_explorer_retry_load"
}
