package com.promenar.nexara.ui.testing

/**
 * 面向自动化测试的稳定语义标识。标识描述控件职责，不依赖本地化文案或动态数据。
 */
object UiTags {
    const val MARKDOWN_WIDE_CONTENT = "markdown_wide_content"
    const val BACKUP_EXPORT = "backup_export"
    const val BACKUP_IMPORT = "backup_import"
    const val BACKUP_OPERATION_STATUS = "backup_operation_status"
    const val CHAT_ROOT = "chat_root"
    const val CHAT_STATE_EMPTY = "chat_state_empty"
    const val CHAT_STATE_LOADING = "chat_state_loading"
    const val CHAT_STATE_GENERATING = "chat_state_generating"
    const val CHAT_STATE_APPROVAL = "chat_state_approval"
    const val CHAT_STATE_ERROR = "chat_state_error"
    const val CHAT_STATE_READY = "chat_state_ready"
    const val CHAT_ASSISTANT_MODEL_METADATA = "chat_assistant_model_metadata"
    const val CHAT_ASSISTANT_TIME_METADATA = "chat_assistant_time_metadata"
    const val CHAT_LOADING_SKELETON = "chat_loading_skeleton"
    const val CHAT_GENERATION_ACTION = "chat_generation_action"
    const val CHAT_COMPOSER = "chat_composer"
    const val CHAT_TASK_PANEL_HEADER = "task_floating_panel_header"
    const val CHAT_TASK_CARD = "chat_task_card"
    const val CHAT_TASK_CAPSULE = "chat_task_capsule"
    const val CHAT_TASK_CONTINUE = "chat_task_continue"
    const val CHAT_TASK_COMPLETE = "chat_task_complete"
    const val CHAT_THINKING_TRACE = "chat_thinking_trace"
    const val CHAT_THINKING_TOGGLE = "chat_thinking_toggle"
    const val CHAT_THINKING_CONTENT = "chat_thinking_content"
    const val CHAT_THINKING_COLLAPSED_CONNECTOR = "chat_thinking_collapsed_connector"
    const val CHAT_INPUT_ISLAND = "chat_input_island"
    const val CHAT_INPUT_BAR_SURFACE = "chat_input_bar_surface"
    const val CHAT_OPTIONS = "chat_options"
    const val CHAT_SESSION_SETTINGS = "chat_session_settings"
    const val CHAT_INPUT = "chat_input"
    const val CHAT_ADD_ATTACHMENT = "chat_add_attachment"
    const val CHAT_ATTACHMENT_MENU = "chat_attachment_menu"
    const val CHAT_ATTACHMENT_DISMISS_LAYER = "chat_attachment_dismiss_layer"
    const val CHAT_ATTACH_MENU_IMAGE = "chat_attach_menu_image"
    const val CHAT_ATTACH_MENU_DOCUMENT = "chat_attach_menu_document"
    const val CHAT_DOCUMENT_CHIPS = "chat_document_chips"
    const val CHAT_DOCUMENT_IMPORTING = "chat_document_importing"
    const val CHAT_MESSAGE_DOCUMENTS = "chat_message_documents"
    const val CHAT_MESSAGE_BRANCH = "chat_message_branch"
    private const val CHAT_DOCUMENT_CHIP_PREFIX = "chat_document_chip:"
    private const val CHAT_DOCUMENT_REMOVE_PREFIX = "chat_document_remove:"

    fun chatDocumentChip(documentId: String): String = CHAT_DOCUMENT_CHIP_PREFIX + documentId
    fun chatDocumentRemove(documentId: String): String = CHAT_DOCUMENT_REMOVE_PREFIX + documentId
    const val PROMPT_EDITOR_INPUT = "prompt_editor_input"
    const val CHAT_MODEL_SELECTOR = "chat_model_selector"
    const val CHAT_MODEL_SELECTOR_VISUAL = "chat_model_selector_visual"
    const val CHAT_TOKEN_INDICATOR = "chat_token_indicator"
    const val CHAT_TOKEN_INDICATOR_VISUAL = "chat_token_indicator_visual"
    const val CHAT_MODEL_LIST = "chat_model_list"
    private const val CHAT_MODEL_OPTION_PREFIX = "chat_model_option:"

    fun chatModelOption(modelId: String): String = CHAT_MODEL_OPTION_PREFIX + modelId
    const val CHAT_APPROVAL_CARD = "chat_approval_card"
    const val CHAT_APPROVAL_REQUIRED = "chat_approval_required"
    const val CHAT_APPROVAL_EXECUTED = "chat_approval_executed"
    const val CHAT_APPROVAL_APPROVE = "chat_approval_approve"
    const val CHAT_APPROVAL_DECLINE = "chat_approval_decline"
    const val NOTIFICATION_PERMISSION_DIALOG = "notification_permission_dialog"
    const val NOTIFICATION_PERMISSION_CONTINUE = "notification_permission_continue"
    const val NOTIFICATION_PERMISSION_FOREGROUND_ONLY = "notification_permission_foreground_only"
    const val SHARE_IMPORT_SHEET = "share_import_sheet"
    const val SHARE_IMPORT_ITEM = "share_import_item"
    const val SHARE_IMPORT_STATUS = "share_import_status"
    const val SHARE_IMPORT_KNOWLEDGE_BASE_TARGET = "share_import_knowledge_base_target"
    const val SHARE_IMPORT_LATER = "share_import_later"
    const val SHARE_IMPORT_CANCEL = "share_import_cancel"
    const val SHARE_IMPORT_ACTION = "share_import_action"

    // ============ Agent Hub ==========
    const val HUB_ROOT = "hub_root"
    const val HUB_ADD_AGENT = "hub_add_agent"
    const val HUB_SEARCH = "hub_search"
    const val HUB_EMPTY_STATE = "hub_empty_state"
    const val HUB_EMPTY_ADD_AGENT = "hub_empty_add_agent"
    const val HUB_AGENT_LIST = "hub_agent_list"
    const val HUB_AGENT_ACTIONS = "hub_agent_actions"
    const val HUB_AGENT_MENU_PIN = "hub_agent_menu_pin"
    const val HUB_AGENT_MENU_EDIT = "hub_agent_menu_edit"
    const val HUB_AGENT_MENU_DELETE = "hub_agent_menu_delete"
    private const val HUB_AGENT_CARD_PREFIX = "hub_agent_card:"

    fun hubAgentCard(agentId: String): String = HUB_AGENT_CARD_PREFIX + agentId
    fun hubAgentActions(agentId: String): String = "$HUB_AGENT_ACTIONS:$agentId"

    // ============ User Settings Home ==========
    const val SETTINGS_ROOT = "settings_root"
    const val SETTINGS_TAB_APP = "settings_tab_app"
    const val SETTINGS_TAB_PROVIDER = "settings_tab_provider"
    const val SETTINGS_APP_LIST = "settings_app_list"
    const val SETTINGS_PROVIDER_LIST = "settings_provider_list"
    const val SETTINGS_PROVIDER_ENTRY = "settings_provider_entry"
    const val SETTINGS_DEFAULT_MODELS_ENTRY = "settings_default_models_entry"
    const val SETTINGS_ADD_PROVIDER = "settings_add_provider"
    const val SETTINGS_PROVIDER_ACTIONS = "settings_provider_actions"
    const val SETTINGS_LOCAL_INFERENCE_ENTRY = "settings_local_inference_entry"
    private const val SETTINGS_PROVIDER_CARD_PREFIX = "settings_provider_card:"

    fun settingsProviderCard(providerId: String): String = SETTINGS_PROVIDER_CARD_PREFIX + providerId
    fun settingsProviderActions(providerId: String): String = "$SETTINGS_PROVIDER_ACTIONS:$providerId"

    // ============ Provider Models ==========
    const val PROVIDER_MODELS_SCREEN_ROOT = "provider_models_screen_root"
    const val PROVIDER_MODELS_SEARCH_FIELD = "provider_models_search"
    const val PROVIDER_MODELS_ACTION_SYNC = "provider_models_action_sync"
    const val PROVIDER_MODELS_ACTION_ADD = "provider_models_action_add"
    const val PROVIDER_MODELS_ACTION_OVERFLOW = "provider_models_action_overflow"
    const val PROVIDER_MODELS_ACTION_DISABLE_ALL = "provider_models_action_disable_all"
    const val PROVIDER_MODELS_ACTION_DELETE_ALL = "provider_models_action_delete_all"
    const val PROVIDER_MODELS_NOTICE = "provider_models_notice"
    const val PROVIDER_MODELS_NOTICE_DISMISS = "provider_models_notice_dismiss"
    const val PROVIDER_MODELS_LIST = "provider_models_list"
    const val PROVIDER_MODELS_STATE_EMPTY = "provider_models_state_empty"
    const val PROVIDER_MODELS_STATE_ERROR = "provider_models_state_error"
    const val PROVIDER_MODELS_STATE_LOADING = "provider_models_state_loading"
    const val PROVIDER_MODELS_STATE_SEARCH_EMPTY = "provider_models_state_search_empty"
    const val PROVIDER_MODELS_ADD_SHEET = "provider_models_add_sheet"
    const val PROVIDER_MODELS_ADD_FORM_LIST = "provider_models_add_form_list"
    const val PROVIDER_MODELS_ADD_ID_FIELD = "provider_models_add_id"
    const val PROVIDER_MODELS_ADD_NAME_FIELD = "provider_models_add_name"
    const val PROVIDER_MODELS_ADD_SUBMIT_BUTTON = "provider_models_add_submit"
    const val PROVIDER_MODELS_DELETE_ALL_CONFIRM_DIALOG = "provider_models_delete_all_confirm_dialog"
    const val PROVIDER_MODELS_DELETE_ALL_CONFIRM_BUTTON = "provider_models_delete_all_confirm"

    private const val PROVIDER_MODELS_MODEL_CARD_PREFIX = "provider_models_card:"
    private const val PROVIDER_MODELS_MODEL_TEST_PREFIX = "provider_models_test:"
    private const val PROVIDER_MODELS_MODEL_DELETE_PREFIX = "provider_models_delete:"
    private const val PROVIDER_MODELS_MODEL_TOGGLE_PREFIX = "provider_models_toggle:"
    private const val PROVIDER_MODELS_MODEL_EXPAND_PREFIX = "provider_models_expand:"
    private const val PROVIDER_MODELS_MODEL_DETAILS_PREFIX = "provider_models_details:"
    private const val PROVIDER_MODELS_MODEL_REMOTE_ID_PREFIX = "provider_models_remote_id:"
    private const val PROVIDER_MODELS_MODEL_NAME_PREFIX = "provider_models_name:"
    private const val PROVIDER_MODELS_MODEL_DELETE_CONFIRM_DIALOG_PREFIX = "provider_models_delete_confirm_dialog:"
    private const val PROVIDER_MODELS_MODEL_DELETE_CONFIRM_PREFIX = "provider_models_delete_confirm:"
    private const val PROVIDER_MODELS_TYPE_PREFIX = "provider_models_type:"
    private const val PROVIDER_MODELS_TYPE_VISUAL_PREFIX = "provider_models_type_visual:"
    private const val PROVIDER_MODELS_CAPABILITY_PREFIX = "provider_models_capability:"
    private const val PROVIDER_MODELS_CAPABILITY_VISUAL_PREFIX = "provider_models_capability_visual:"
    private const val PROVIDER_MODELS_CONTEXT_PREFIX = "provider_models_context:"
    private const val PROVIDER_MODELS_EDITOR_SHEET_PREFIX = "provider_models_editor_sheet:"
    private const val PROVIDER_MODELS_EDITOR_LIST_PREFIX = "provider_models_editor_list:"
    private const val PROVIDER_MODELS_EDITOR_CLOSE_PREFIX = "provider_models_editor_close:"
    private const val PROVIDER_MODELS_EDITOR_TEST_PREFIX = "provider_models_editor_test:"
    private const val PROVIDER_MODELS_EDITOR_CANCEL_PREFIX = "provider_models_editor_cancel:"
    private const val PROVIDER_MODELS_EDITOR_SOURCE_PREFIX = "provider_models_editor_source:"
    private const val PROVIDER_MODELS_EDITOR_DELETE_PREFIX = "provider_models_editor_delete:"
    private const val PROVIDER_MODELS_EDITOR_DELETE_CONFIRM_DIALOG_PREFIX =
        "provider_models_editor_delete_confirm_dialog:"
    private const val PROVIDER_MODELS_EDITOR_DELETE_CONFIRM_PREFIX = "provider_models_editor_delete_confirm:"

    fun providerModelsModelCard(modelId: String): String = "$PROVIDER_MODELS_MODEL_CARD_PREFIX$modelId"
    fun providerModelsTestAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_TEST_PREFIX$modelId"
    fun providerModelsDeleteAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_DELETE_PREFIX$modelId"
    fun providerModelsToggleAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_TOGGLE_PREFIX$modelId"
    fun providerModelsExpandAction(modelId: String): String = "$PROVIDER_MODELS_MODEL_EXPAND_PREFIX$modelId"
    fun providerModelsDetails(modelId: String): String = "$PROVIDER_MODELS_MODEL_DETAILS_PREFIX$modelId"
    fun providerModelsRemoteId(modelId: String): String = "$PROVIDER_MODELS_MODEL_REMOTE_ID_PREFIX$modelId"
    fun providerModelsNameField(modelId: String): String = "$PROVIDER_MODELS_MODEL_NAME_PREFIX$modelId"
    fun providerModelsDeleteConfirmDialog(modelId: String): String =
        "$PROVIDER_MODELS_MODEL_DELETE_CONFIRM_DIALOG_PREFIX$modelId"
    fun providerModelsDeleteConfirmButton(modelId: String): String =
        "$PROVIDER_MODELS_MODEL_DELETE_CONFIRM_PREFIX$modelId"
    fun providerModelsTypeAction(modelId: String, type: String): String =
        "$PROVIDER_MODELS_TYPE_PREFIX$modelId:$type"
    fun providerModelsTypeVisual(modelId: String, type: String): String =
        "$PROVIDER_MODELS_TYPE_VISUAL_PREFIX$modelId:$type"
    fun providerModelsCapabilityAction(modelId: String, capability: String): String =
        "$PROVIDER_MODELS_CAPABILITY_PREFIX$modelId:$capability"
    fun providerModelsCapabilityVisual(modelId: String, capability: String): String =
        "$PROVIDER_MODELS_CAPABILITY_VISUAL_PREFIX$modelId:$capability"
    fun providerModelsContextField(modelId: String): String = "$PROVIDER_MODELS_CONTEXT_PREFIX$modelId"
    fun providerModelsEditorSheet(modelId: String): String = "$PROVIDER_MODELS_EDITOR_SHEET_PREFIX$modelId"
    fun providerModelsEditorList(modelId: String): String = "$PROVIDER_MODELS_EDITOR_LIST_PREFIX$modelId"
    fun providerModelsEditorCloseAction(modelId: String): String = "$PROVIDER_MODELS_EDITOR_CLOSE_PREFIX$modelId"
    fun providerModelsEditorTestAction(modelId: String): String = "$PROVIDER_MODELS_EDITOR_TEST_PREFIX$modelId"
    fun providerModelsEditorCancelAction(modelId: String): String = "$PROVIDER_MODELS_EDITOR_CANCEL_PREFIX$modelId"
    fun providerModelsEditorSource(modelId: String): String = "$PROVIDER_MODELS_EDITOR_SOURCE_PREFIX$modelId"
    fun providerModelsEditorDeleteAction(modelId: String): String = "$PROVIDER_MODELS_EDITOR_DELETE_PREFIX$modelId"
    fun providerModelsEditorDeleteConfirmDialog(modelId: String): String =
        "$PROVIDER_MODELS_EDITOR_DELETE_CONFIRM_DIALOG_PREFIX$modelId"
    fun providerModelsEditorDeleteConfirmButton(modelId: String): String =
        "$PROVIDER_MODELS_EDITOR_DELETE_CONFIRM_PREFIX$modelId"

    // ============ RAG Home ==========
    const val RAG_HOME_ROOT = "RAG_HOME_ROOT"
    const val RAG_HOME_SEARCH = "RAG_HOME_SEARCH"
    const val RAG_HOME_TAB_DOCUMENTS = "RAG_HOME_TAB_DOCUMENTS"
    const val RAG_HOME_TAB_MEMORY = "RAG_HOME_TAB_MEMORY"
    const val RAG_HOME_TAB_GRAPH = "RAG_HOME_TAB_GRAPH"
    const val RAG_HOME_CONFIG = "RAG_HOME_CONFIG"
    const val RAG_HOME_NEW_FOLDER = "RAG_HOME_NEW_FOLDER"
    const val RAG_HOME_UPLOAD = "RAG_HOME_UPLOAD"
    const val RAG_HOME_DOCUMENTS_CONTENT = "RAG_HOME_DOCUMENTS_CONTENT"
    const val RAG_HOME_MEMORY_CONTENT = "RAG_HOME_MEMORY_CONTENT"
    const val RAG_HOME_INDEXING_NOTICE = "RAG_HOME_INDEXING_NOTICE"
    const val RAG_HOME_NEW_FOLDER_DIALOG = "RAG_HOME_NEW_FOLDER_DIALOG"
    const val RAG_HOME_MOVE_SHEET = "RAG_HOME_MOVE_SHEET"
    const val RAG_HOME_SELECTION_BAR = "RAG_HOME_SELECTION_BAR"
    const val RAG_HOME_CLEAR_SELECTION = "RAG_HOME_CLEAR_SELECTION"
    const val RAG_HOME_MOVE_SELECTION = "RAG_HOME_MOVE_SELECTION"
    const val RAG_HOME_REINDEX_SELECTION = "RAG_HOME_REINDEX_SELECTION"
    const val RAG_HOME_DELETE_SELECTION = "RAG_HOME_DELETE_SELECTION"
    const val RAG_HOME_DELETE_CONFIRM_DIALOG = "RAG_HOME_DELETE_CONFIRM_DIALOG"
    const val RAG_HOME_DELETE_CONFIRM_BUTTON = "RAG_HOME_DELETE_CONFIRM_BUTTON"
    const val RAG_FOLDER_DOCUMENT_ITEM = "RAG_FOLDER_DOCUMENT_ITEM"
    const val RAG_FOLDER_ROOT = "RAG_FOLDER_ROOT"
    const val RAG_FOLDER_CONTENT = "RAG_FOLDER_CONTENT"
    const val RAG_FOLDER_BACK = "RAG_FOLDER_BACK"
    const val RAG_FOLDER_SELECT_ALL = "RAG_FOLDER_SELECT_ALL"
    const val RAG_FOLDER_SELECT_ALL_MENU_ITEM = "RAG_FOLDER_SELECT_ALL_MENU_ITEM"
    const val RAG_FOLDER_SELECTION_BAR = "RAG_FOLDER_SELECTION_BAR"
    const val RAG_FOLDER_CLEAR_SELECTION = "RAG_FOLDER_CLEAR_SELECTION"
    const val RAG_FOLDER_MOVE_SELECTION = "RAG_FOLDER_MOVE_SELECTION"
    const val RAG_FOLDER_REINDEX_SELECTION = "RAG_FOLDER_REINDEX_SELECTION"
    const val RAG_FOLDER_DELETE_SELECTION = "RAG_FOLDER_DELETE_SELECTION"
    const val RAG_FOLDER_MOVE_SHEET = "RAG_FOLDER_MOVE_SHEET"
    const val RAG_FOLDER_MOVE_LIST = "RAG_FOLDER_MOVE_LIST"
    const val RAG_FOLDER_DELETE_CONFIRM_DIALOG = "RAG_FOLDER_DELETE_CONFIRM_DIALOG"
    const val RAG_FOLDER_DELETE_CONFIRM_BUTTON = "RAG_FOLDER_DELETE_CONFIRM_BUTTON"
    const val RAG_FOLDER_UPLOAD = "RAG_FOLDER_UPLOAD"

    // ============ RAG Details ==========
    const val RAG_DETAILS_ROOT = "RAG_DETAILS_ROOT"
    const val RAG_DETAILS_TAB_RETRIEVED = "RAG_DETAILS_TAB_RETRIEVED"
    const val RAG_DETAILS_TAB_WEB = "RAG_DETAILS_TAB_WEB"
    const val RAG_DETAILS_TAB_KG = "RAG_DETAILS_TAB_KG"
    const val RAG_DETAILS_LIST = "RAG_DETAILS_LIST"
    const val RAG_DETAILS_LINK_ERROR = "RAG_DETAILS_LINK_ERROR"
    const val RAG_DETAILS_LINK_RETRY = "RAG_DETAILS_LINK_RETRY"
    const val RAG_PROGRESS_CARD = "RAG_PROGRESS_CARD"
    private const val RAG_DETAILS_REFERENCE_ITEM_PREFIX = "RAG_DETAILS_REFERENCE_ITEM:"
    private const val RAG_DETAILS_WEB_ITEM_PREFIX = "RAG_DETAILS_WEB_ITEM:"
    private const val RAG_DETAILS_KG_PATH_PREFIX = "RAG_DETAILS_KG_PATH:"
    private const val RAG_DETAILS_KG_RELATION_PREFIX = "RAG_DETAILS_KG_RELATION:"

    fun ragDetailsReferenceItem(index: Int): String = "$RAG_DETAILS_REFERENCE_ITEM_PREFIX$index"
    fun ragDetailsWebItem(index: Int): String = "$RAG_DETAILS_WEB_ITEM_PREFIX$index"
    fun ragDetailsKgPath(index: Int): String = "$RAG_DETAILS_KG_PATH_PREFIX$index"
    fun ragDetailsKgRelation(pathIndex: Int, edgeIndex: Int): String =
        "$RAG_DETAILS_KG_RELATION_PREFIX$pathIndex:$edgeIndex"

    // ============ Doc Editor ==========
    const val DOC_EDITOR_ROOT = "doc_editor_root"
    const val DOC_EDITOR_BACK = "doc_editor_back"
    const val DOC_EDITOR_IDENTITY = "doc_editor_identity"
    const val DOC_EDITOR_TITLE_INPUT = "doc_editor_title_input"
    const val DOC_EDITOR_METADATA = "doc_editor_metadata"
    const val DOC_EDITOR_STATISTICS = "doc_editor_statistics"
    const val DOC_EDITOR_SAVE = "doc_editor_save"
    const val DOC_EDITOR_MODE_SELECTOR = "doc_editor_mode_selector"
    const val DOC_EDITOR_MODE_EDIT = "doc_editor_mode_edit"
    const val DOC_EDITOR_MODE_PREVIEW = "doc_editor_mode_preview"
    const val DOC_EDITOR_MODE_SPLIT = "doc_editor_mode_split"
    const val DOC_EDITOR_MAIN_PANE = "doc_editor_main_pane"
    const val DOC_EDITOR_SPLIT_DIVIDER = "doc_editor_split_divider"
    const val DOC_EDITOR_INPUT = "doc_editor_input"
    const val DOC_EDITOR_PREVIEW = "doc_editor_preview"
    const val DOC_EDITOR_STATUS = "doc_editor_status"
    const val DOC_EDITOR_STATE_LOADING = "doc_editor_state_loading"
    const val DOC_EDITOR_STATE_LOAD_ERROR = "doc_editor_state_load_error"
    const val DOC_EDITOR_STATE_NOT_FOUND = "doc_editor_state_not_found"
    const val DOC_EDITOR_STATE_SAVING = "doc_editor_state_saving"
    const val DOC_EDITOR_STATE_SAVE_ERROR = "doc_editor_state_save_error"
    const val DOC_EDITOR_STATE_CONFLICT = "doc_editor_state_conflict"
    const val DOC_EDITOR_STATE_LARGE_FILE = "doc_editor_state_large_file"
    const val DOC_EDITOR_STATE_PERFORMANCE_PROTECTED = "doc_editor_state_performance_protected"
    const val DOC_EDITOR_COPY_PROTECTED_FULL = "doc_editor_copy_protected_full"
    const val DOC_EDITOR_RETRY_LOAD = "doc_editor_retry_load"
    const val DOC_EDITOR_RETRY_SAVE = "doc_editor_retry_save"
    const val DOC_EDITOR_COPY_LOCAL = "doc_editor_copy_local"
    const val DOC_EDITOR_USE_WORKSPACE_TITLE = "doc_editor_use_workspace_title"
    const val DOC_EDITOR_RETRY_MY_TITLE = "doc_editor_retry_my_title"
    const val DOC_EDITOR_REQUEST_RELOAD = "doc_editor_request_reload"
    const val DOC_EDITOR_WARNING_DISMISS = "doc_editor_warning_dismiss"
    const val DOC_EDITOR_DISCARD_DIALOG = "doc_editor_discard_dialog"
    const val DOC_EDITOR_DISCARD_CONFIRM = "doc_editor_discard_confirm"
    const val DOC_EDITOR_DISCARD_CANCEL = "doc_editor_discard_cancel"
    const val DOC_EDITOR_RELOAD_DIALOG = "doc_editor_reload_dialog"
    const val DOC_EDITOR_RELOAD_CONFIRM = "doc_editor_reload_confirm"
    const val DOC_EDITOR_RELOAD_CANCEL = "doc_editor_reload_cancel"

    // ============ Resource Explorer ==========
    const val RESOURCE_EXPLORER_ROOT = "resource_explorer_root"
    const val RESOURCE_EXPLORER_SEARCH = "resource_explorer_search"
    const val RESOURCE_EXPLORER_IMPORT = "resource_explorer_import"
    const val RESOURCE_EXPLORER_IMPORT_RESULTS = "resource_explorer_import_results"
    const val RESOURCE_EXPLORER_CLEAR_RESULTS = "resource_explorer_clear_results"
    const val RESOURCE_EXPLORER_TAB_FILES = "resource_explorer_tab_files"
    const val RESOURCE_EXPLORER_TAB_RECYCLE_BIN = "resource_explorer_tab_recycle_bin"
    const val RESOURCE_EXPLORER_PAGER = "resource_explorer_pager"
    const val RESOURCE_EXPLORER_SESSION_STATUS = "resource_explorer_session_status"
    const val RESOURCE_EXPLORER_RETRY_LOAD = "resource_explorer_retry_load"
    const val RESOURCE_EXPLORER_RECYCLE_LIST = "recycle_bin_list"
    const val RESOURCE_EXPLORER_RECYCLE_CLEANUP_NOTICE = "recycle_bin_cleanup_notice"
    const val RESOURCE_EXPLORER_RECYCLE_RESTORE_ALL = "recycle_bin_restore_all"
    const val RESOURCE_EXPLORER_RECYCLE_DELETE_ALL = "recycle_bin_delete_all"
    const val RESOURCE_EXPLORER_RECYCLE_EMPTY = "recycle_bin_empty_state"
    const val RESOURCE_EXPLORER_RECYCLE_OPERATION_STATUS = "recycle_bin_operation_status"
    const val RESOURCE_EXPLORER_RECYCLE_OPERATION_NOTICE = "recycle_bin_operation_notice"
    const val RESOURCE_EXPLORER_RECYCLE_OPERATION_RETRY = "recycle_bin_operation_retry"
    const val RESOURCE_EXPLORER_RECYCLE_OPERATION_CLEAR = "recycle_bin_operation_clear"
    const val RESOURCE_EXPLORER_RECYCLE_DELETE_CONFIRM = "recycle_bin_delete_confirm"
    const val RESOURCE_EXPLORER_RECYCLE_EMPTY_CONFIRM = "recycle_bin_empty_confirm"

    fun resourceExplorerImportStatus(uri: String) = "resource_explorer_import_status:$uri"
    fun resourceExplorerImportRetry(uri: String) = "resource_explorer_import_retry:$uri"
    fun resourceExplorerRecycleRestore(uuid: String) = "recycle_bin_restore:$uuid"
    fun resourceExplorerRecycleDelete(uuid: String) = "recycle_bin_delete:$uuid"

    private const val FILE_NODE_OPTIONS_PREFIX = "file_node_options:"
    private const val FILE_NODE_REINDEX_PREFIX = "file_node_reindex:"
    private const val FILE_NODE_MULTI_SELECT_PREFIX = "file_node_multi_select:"

    fun fileNodeOptions(fileId: String): String = "$FILE_NODE_OPTIONS_PREFIX$fileId"
    fun fileNodeReindex(fileId: String): String = "$FILE_NODE_REINDEX_PREFIX$fileId"
    fun fileNodeMultiSelect(fileId: String): String = "$FILE_NODE_MULTI_SELECT_PREFIX$fileId"
}
